eslint:
  enabled: true
  config_file: .eslintrc
scss:
  enabled: false
fail_on_violaions: true
ignore_file: public/emoji/css/cover.scss
ignore_file: public/emoji/css/cover.css
ignore_file: public/emoji/lib/js/emoji-picker.coffee
ignore_file: .eslintignore