language: node_js

node_js: stable

services:
  - mongodb

before_script:
  - npm install
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

notifications:
   slack: andela:FzLbplkwSghKxRUKKqTyvBpd

script:
  - gulp

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js